name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v6.0.3

      - name: Set up Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod

      - name: Run CI
        run: go run ./cmd/scripts ci
